package pruebadb.example.dj.com.pruebadb.pruebadb.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "DATA_SERVICE".
 */
@Entity
public class DataService {

    @Id(autoincrement = true)
    private Long id;
    private String descripcion;
    private String categoria;
    private String telefono;
    private String zipCode;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public DataService() {
    }

    public DataService(Long id) {
        this.id = id;
    }

    @Generated
    public DataService(Long id, String descripcion, String categoria, String telefono, String zipCode) {
        this.id = id;
        this.descripcion = descripcion;
        this.categoria = categoria;
        this.telefono = telefono;
        this.zipCode = zipCode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getCategoria() {
        return categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
