package pruebadb.example.dj.com.pruebadb.pruebadb.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PERMISO_TAREAS_USER".
 */
@Entity
public class PermisoTareasUser {
    private boolean permiso;
    private long idUser;
    private long idTarea;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public PermisoTareasUser() {
    }

    @Generated
    public PermisoTareasUser(boolean permiso, long idUser, long idTarea) {
        this.permiso = permiso;
        this.idUser = idUser;
        this.idTarea = idTarea;
    }

    public boolean getPermiso() {
        return permiso;
    }

    public void setPermiso(boolean permiso) {
        this.permiso = permiso;
    }

    public long getIdUser() {
        return idUser;
    }

    public void setIdUser(long idUser) {
        this.idUser = idUser;
    }

    public long getIdTarea() {
        return idTarea;
    }

    public void setIdTarea(long idTarea) {
        this.idTarea = idTarea;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
