package pruebadb.example.dj.com.pruebadb.pruebadb.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RELACION_USUARIO_TAREA".
*/
public class RelacionUsuarioTareaDao extends AbstractDao<RelacionUsuarioTarea, Void> {

    public static final String TABLENAME = "RELACION_USUARIO_TAREA";

    /**
     * Properties of entity RelacionUsuarioTarea.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Estado = new Property(0, String.class, "estado", false, "ESTADO");
        public final static Property IdUser = new Property(1, long.class, "idUser", false, "ID_USER");
        public final static Property IdTarea = new Property(2, long.class, "idTarea", false, "ID_TAREA");
    }

    private Query<RelacionUsuarioTarea> usuario_UserRefQuery;
    private Query<RelacionUsuarioTarea> tarea_TareaRefQuery;

    public RelacionUsuarioTareaDao(DaoConfig config) {
        super(config);
    }
    
    public RelacionUsuarioTareaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RELACION_USUARIO_TAREA\" (" + //
                "\"ESTADO\" TEXT NOT NULL ," + // 0: estado
                "\"ID_USER\" INTEGER NOT NULL ," + // 1: idUser
                "\"ID_TAREA\" INTEGER NOT NULL );"); // 2: idTarea
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RELACION_USUARIO_TAREA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RelacionUsuarioTarea entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getEstado());
        stmt.bindLong(2, entity.getIdUser());
        stmt.bindLong(3, entity.getIdTarea());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RelacionUsuarioTarea entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getEstado());
        stmt.bindLong(2, entity.getIdUser());
        stmt.bindLong(3, entity.getIdTarea());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public RelacionUsuarioTarea readEntity(Cursor cursor, int offset) {
        RelacionUsuarioTarea entity = new RelacionUsuarioTarea( //
            cursor.getString(offset + 0), // estado
            cursor.getLong(offset + 1), // idUser
            cursor.getLong(offset + 2) // idTarea
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RelacionUsuarioTarea entity, int offset) {
        entity.setEstado(cursor.getString(offset + 0));
        entity.setIdUser(cursor.getLong(offset + 1));
        entity.setIdTarea(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(RelacionUsuarioTarea entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(RelacionUsuarioTarea entity) {
        return null;
    }

    @Override
    public boolean hasKey(RelacionUsuarioTarea entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "userRef" to-many relationship of Usuario. */
    public List<RelacionUsuarioTarea> _queryUsuario_UserRef(long idUser) {
        synchronized (this) {
            if (usuario_UserRefQuery == null) {
                QueryBuilder<RelacionUsuarioTarea> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdUser.eq(null));
                usuario_UserRefQuery = queryBuilder.build();
            }
        }
        Query<RelacionUsuarioTarea> query = usuario_UserRefQuery.forCurrentThread();
        query.setParameter(0, idUser);
        return query.list();
    }

    /** Internal query to resolve the "tareaRef" to-many relationship of Tarea. */
    public List<RelacionUsuarioTarea> _queryTarea_TareaRef(long idTarea) {
        synchronized (this) {
            if (tarea_TareaRefQuery == null) {
                QueryBuilder<RelacionUsuarioTarea> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdTarea.eq(null));
                tarea_TareaRefQuery = queryBuilder.build();
            }
        }
        Query<RelacionUsuarioTarea> query = tarea_TareaRefQuery.forCurrentThread();
        query.setParameter(0, idTarea);
        return query.list();
    }

}
