package pruebadb.example.dj.com.pruebadb.pruebadb.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TAREA".
*/
public class TareaDao extends AbstractDao<Tarea, Long> {

    public static final String TABLENAME = "TAREA";

    /**
     * Properties of entity Tarea.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Tarea_id = new Property(1, String.class, "tarea_id", false, "TAREA_ID");
        public final static Property Descripcion = new Property(2, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property Duracion = new Property(3, int.class, "duracion", false, "DURACION");
    }

    private DaoSession daoSession;


    public TareaDao(DaoConfig config) {
        super(config);
    }
    
    public TareaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TAREA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TAREA_ID\" TEXT NOT NULL ," + // 1: tarea_id
                "\"DESCRIPCION\" TEXT NOT NULL ," + // 2: descripcion
                "\"DURACION\" INTEGER NOT NULL );"); // 3: duracion
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TAREA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Tarea entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTarea_id());
        stmt.bindString(3, entity.getDescripcion());
        stmt.bindLong(4, entity.getDuracion());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Tarea entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTarea_id());
        stmt.bindString(3, entity.getDescripcion());
        stmt.bindLong(4, entity.getDuracion());
    }

    @Override
    protected final void attachEntity(Tarea entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Tarea readEntity(Cursor cursor, int offset) {
        Tarea entity = new Tarea( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // tarea_id
            cursor.getString(offset + 2), // descripcion
            cursor.getInt(offset + 3) // duracion
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Tarea entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTarea_id(cursor.getString(offset + 1));
        entity.setDescripcion(cursor.getString(offset + 2));
        entity.setDuracion(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Tarea entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Tarea entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Tarea entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
